services:
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./tsconfig.json:/app/tsconfig.json
      - ./craco.config.js:/app/craco.config.js
      - ./.env:/app/.env
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=https://fakestoreapi.com
      - REACT_APP_DEVELOPER="Студент 2КІ-24м Сеник Юрій"
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    command: yarn start
    restart: unless-stopped
